// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/amman-homepage/ScrollingHome.tsx": () => import("../components/mockups/amman-homepage/ScrollingHome.tsx")
};
