-- ============================================
-- Virtual Art Space — Full Database Seed
-- ============================================
-- Run this in your production PostgreSQL console.
-- It wipes ALL existing data and repopulates every table.
--
-- Password for all demo users: demo1234
-- (hash: $2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe)
-- ============================================

BEGIN;

-- 1. Clear everything
TRUNCATE TABLE artworks, galleries, profiles, users RESTART IDENTITY CASCADE;

-- 2. Users (10 artists)
INSERT INTO users (email, username, password_hash) VALUES
  ('layla@virtualartspace.jo',  'layla.nabulsi',  '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('omar@virtualartspace.jo',   'omar.khalil',    '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('sana@virtualartspace.jo',   'sana.masri',     '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('tariq@virtualartspace.jo',  'tariq.hamdan',   '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('reem@virtualartspace.jo',   'reem.aziz',      '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('khalid@virtualartspace.jo', 'khalid.barakat', '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('dina@virtualartspace.jo',   'dina.sabbagh',   '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('yusuf@virtualartspace.jo',  'yusuf.nassar',   '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('nour@virtualartspace.jo',   'nour.jamal',     '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe'),
  ('ibrahim@virtualartspace.jo','ibrahim.qasim',  '$2b$10$oMzCPU6S3foCKazdR2OGf.bkZjZ87wrWkWDTjdzkwucU04KYdDBRe');

-- 3. Profiles
INSERT INTO profiles (user_id, display_name, bio, avatar_url) VALUES
  (1, 'Layla Nabulsi', 'Layla grew up in Jabal al-Weibdeh, Amman, where limestone walls and hanging jasmine shaped her visual language. Her practice explores the tension between tradition and contemporary Arab identity through large-format oil painting. She has exhibited across Amman, Beirut, and Berlin.', 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80'),
  (2, 'Omar Khalil', 'Omar''s geometric abstractions draw directly from the tilework of the Umayyad Mosque and the ornamental patterns he studied as a child in his family''s tile workshop in downtown Amman. He works in acrylic and digital print, layering Islamic geometry with modernist minimalism.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80'),
  (3, 'Sana al-Masri', 'Sana al-Masri is a Palestinian-Jordanian photographer whose lens turns to the everyday poetry of Amman''s streets — the chai vendors on Rainbow Street, the Roman Theatre at dusk, the balconies draped in laundry. Her images are quiet declarations of presence.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80'),
  (4, 'Tariq Hamdan', 'Tariq studied at the Faculty of Fine Arts at the University of Jordan and spent three years in residence at studios in Florence and Cairo. His oil-on-canvas work merges classical European technique with Arab subject matter, reimagining the Grand Tour through a Levantine eye.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80'),
  (5, 'Reem Aziz', 'Reem''s practice is rooted in Arabic calligraphy and its transformation into abstract mark-making. She writes to paint — her strokes begin as letters from Rumi or Mahmoud Darwish that dissolve into pure form. Each work is a meditation on language, silence, and the body.', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80'),
  (6, 'Khalid Barakat', 'Khalid Barakat makes sculpture and mixed-media installations that respond to Jordan''s archaeological landscape — Petra, Jerash, the copper mines of Wadi Faynan. He uses earth, found clay, and bronze casting alongside digital fabrication in his Amman studio.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80'),
  (7, 'Dina Sabbagh', 'Dina is a textile artist and painter who learned to weave from her grandmother in Salt, Jordan. Her canvases are hybrid objects — painted, stitched, and unravelled — exploring the gendered labour of making in the Arab world and the intimacy woven into domestic craft.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80'),
  (8, 'Yusuf Nassar', 'Yusuf Nassar''s digital works interrogate how the Arab city is built and demolished — mapping Amman''s informal neighbourhoods, contested spaces, and the architecture of displacement through data-driven generative art. He collaborates with urban planners, architects, and musicians.', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&q=80'),
  (9, 'Nour Jamal', 'Nour is a painter and printmaker whose work centres on the flora and fauna of Jordan — the black irises of the highlands, the bougainvillea tumbling down Aqaba walls, the starlings over Wadi Rum. Her palette borrows from the natural pigments of the earth beneath her feet.', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&q=80'),
  (10, 'Ibrahim Qasim', 'Ibrahim Qasim works at the intersection of conceptual art and Sufi philosophy. His installations — often using light, mirror, and sound — invite the viewer into states of contemplation and dissolution. He has shown at Darat al-Funun, the Jordan National Gallery, and Art Dubai.', 'https://images.unsplash.com/photo-1488161628813-04466f872be2?w=200&q=80');

-- 4. Galleries (3 per artist = 30 total, all published)
INSERT INTO galleries (user_id, title, description, room_theme, published, slug, room_seed, room_mode, room_size, decoration_level) VALUES
  -- Artist 1: Layla
  (1, 'Echoes of the Citadel', 'A curated exhibition by Layla Nabulsi. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'dark_void', true, 'echoes-of-the-citadel-a3f2', 2847, 'basic', 5, 5),
  (1, 'Between Two Rivers', 'A curated exhibition by Layla Nabulsi. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'neon_grid', true, 'between-two-rivers-b7e1', 9153, 'extended', 6, 7),
  (1, 'Limestone & Light', 'A curated exhibition by Layla Nabulsi. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'purple_mist', true, 'limestone-and-light-c4d8', 4621, 'basic', 4, 3),
  -- Artist 2: Omar
  (2, 'The Weight of Jasmine', 'A curated exhibition by Omar Khalil. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'white_cube', true, 'the-weight-of-jasmine-d9a3', 7384, 'extended', 5, 6),
  (2, 'Geometric Meditations', 'A curated exhibition by Omar Khalil. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'concrete_bunker', true, 'geometric-meditations-e1b5', 1592, 'basic', 6, 4),
  (2, 'Wadi Rum Visions', 'A curated exhibition by Omar Khalil. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'dark_void', true, 'wadi-rum-visions-f2c7', 5836, 'extended', 4, 5),
  -- Artist 3: Sana
  (3, 'Amman by Night', 'A curated exhibition by Sana al-Masri. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'neon_grid', true, 'amman-by-night-g3d9', 4017, 'basic', 5, 7),
  (3, 'Calligraphy in Motion', 'A curated exhibition by Sana al-Masri. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'purple_mist', true, 'calligraphy-in-motion-h4e2', 9275, 'extended', 6, 3),
  (3, 'The Roman Arch Revisited', 'A curated exhibition by Sana al-Masri. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'white_cube', true, 'the-roman-arch-revisited-i5f4', 6380, 'basic', 4, 6),
  -- Artist 4: Tariq
  (4, 'Urban Palimpsest', 'A curated exhibition by Tariq Hamdan. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'concrete_bunker', true, 'urban-palimpsest-j6g8', 2154, 'extended', 5, 4),
  (4, 'Shades of Umber', 'A curated exhibition by Tariq Hamdan. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'dark_void', true, 'shades-of-umber-k7h1', 8493, 'basic', 6, 5),
  (4, 'Beyond the Old City', 'A curated exhibition by Tariq Hamdan. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'neon_grid', true, 'beyond-the-old-city-l8i3', 5728, 'extended', 4, 7),
  -- Artist 5: Reem
  (5, 'Salt & Stone', 'A curated exhibition by Reem Aziz. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'purple_mist', true, 'salt-and-stone-m9j6', 3941, 'basic', 5, 3),
  (5, 'Fragments of Memory', 'A curated exhibition by Reem Aziz. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'white_cube', true, 'fragments-of-memory-n0k2', 7168, 'extended', 6, 6),
  (5, 'Kufic Variations', 'A curated exhibition by Reem Aziz. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'concrete_bunker', true, 'kufic-variations-o1l5', 2583, 'basic', 4, 4),
  -- Artist 6: Khalid
  (6, 'Shadows on White', 'A curated exhibition by Khalid Barakat. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'dark_void', true, 'shadows-on-white-p2m8', 6814, 'extended', 5, 7),
  (6, 'The Olive Grove', 'A curated exhibition by Khalid Barakat. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'neon_grid', true, 'the-olive-grove-q3n1', 1437, 'basic', 6, 5),
  (6, 'Desert Chromatics', 'A curated exhibition by Khalid Barakat. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'purple_mist', true, 'desert-chromatics-r4o6', 9052, 'extended', 4, 3),
  -- Artist 7: Dina
  (7, 'Modern Arabesque', 'A curated exhibition by Dina Sabbagh. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'white_cube', true, 'modern-arabesque-s5p9', 5279, 'basic', 5, 6),
  (7, 'Threshold', 'A curated exhibition by Dina Sabbagh. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'concrete_bunker', true, 'threshold-t6q3', 3684, 'extended', 6, 4),
  (7, 'Dead Sea Reflections', 'A curated exhibition by Dina Sabbagh. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'dark_void', true, 'dead-sea-reflections-u7r5', 7910, 'basic', 4, 7),
  -- Artist 8: Yusuf
  (8, 'The Copper Hills', 'A curated exhibition by Yusuf Nassar. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'neon_grid', true, 'the-copper-hills-v8s2', 2346, 'extended', 5, 5),
  (8, 'Petra at Dawn', 'A curated exhibition by Yusuf Nassar. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'purple_mist', true, 'petra-at-dawn-w9t7', 6581, 'basic', 6, 3),
  (8, 'Jabal Qal''a', 'A curated exhibition by Yusuf Nassar. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'white_cube', true, 'jabal-qala-x0u4', 4823, 'extended', 4, 6),
  -- Artist 9: Nour
  (9, 'Aqaba Blue', 'A curated exhibition by Nour Jamal. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'concrete_bunker', true, 'aqaba-blue-y1v8', 3157, 'basic', 5, 4),
  (9, 'The Black Iris Garden', 'A curated exhibition by Nour Jamal. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'dark_void', true, 'the-black-iris-garden-z2w5', 7496, 'extended', 6, 7),
  (9, 'Jerash in Ruins', 'A curated exhibition by Nour Jamal. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'neon_grid', true, 'jerash-in-ruins-a3x1', 2684, 'basic', 4, 5),
  -- Artist 10: Ibrahim
  (10, 'Wadi Faynan Gold', 'A curated exhibition by Ibrahim Qasim. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'purple_mist', true, 'wadi-faynan-gold-b4y6', 5930, 'extended', 5, 6),
  (10, 'Bougainvillea Fall', 'A curated exhibition by Ibrahim Qasim. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'white_cube', true, 'bougainvillea-fall-c5z2', 4175, 'basic', 6, 3),
  (10, 'Letters to the Levant', 'A curated exhibition by Ibrahim Qasim. This gallery presents works exploring the artist''s ongoing dialogue with Amman''s visual and cultural landscape.', 'concrete_bunker', true, 'letters-to-the-levant-d6a8', 8352, 'extended', 4, 4);

-- 5. Artworks (5 per gallery = 150 total)
INSERT INTO artworks (gallery_id, title, description, image_url, artist_name, year, medium, dimensions, x_position, y_position, z_position, rotation, scale, is_manually_placed) VALUES
  -- Gallery 1: Echoes of the Citadel (Layla)
  (1, 'Amber at Dusk', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1000px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg', 'Layla Nabulsi', '2022', 'Oil on canvas', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (1, 'The Limestone Veil', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/1000px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg', 'Layla Nabulsi', '2020', 'Watercolour on paper', '60 × 80 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (1, 'Between Walls', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/800px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg', 'Layla Nabulsi', '2023', 'Digital print', '90 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (1, 'Jasmine Memory', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_Scream.jpg/800px-The_Scream.jpg', 'Layla Nabulsi', '2021', 'Acrylic on wood', '200 × 150 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (1, 'Golden Hour Study', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg', 'Layla Nabulsi', '2024', 'Mixed media', '150 × 100 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 2: Between Two Rivers (Layla)
  (2, 'Citadel Fragment', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg', 'Layla Nabulsi', '2019', 'Ink on paper', '50 × 70 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (2, 'Wadi Floor', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/The_Lady_of_Shalott%2C_by_John_William_Waterhouse.jpg/800px-The_Lady_of_Shalott%2C_by_John_William_Waterhouse.jpg', 'Layla Nabulsi', '2022', 'Photography', '180 × 120 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (2, 'Ink & Silence', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Klimt_The_Kiss.jpg/800px-Klimt_The_Kiss.jpg', 'Layla Nabulsi', '2020', 'Charcoal on linen', '120 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (2, 'Geometric Prayer', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg/800px-Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg', 'Layla Nabulsi', '2023', 'Gouache on board', '100 × 70 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (2, 'Amman Rooftops', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Vassily_Kandinsky%2C_1913_-_Composition_7.jpg/1000px-Vassily_Kandinsky%2C_1913_-_Composition_7.jpg', 'Layla Nabulsi', '2024', 'Screen print', '80 × 60 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 3: Limestone & Light (Layla)
  (3, 'Desert Hymn', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Wassily_Kandinsky%2C_1926_-_Several_Circles%2C_Gugg_0910_25.jpg/800px-Wassily_Kandinsky%2C_1926_-_Several_Circles%2C_Gugg_0910_25.jpg', 'Layla Nabulsi', '2021', 'Encaustic on panel', '60 × 80 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (3, 'The Fig Tree', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg/1000px-Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg', 'Layla Nabulsi', '2018', 'Oil on canvas', '200 × 150 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (3, 'Shadow Letter', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/800px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg', 'Layla Nabulsi', '2023', 'Watercolour on paper', '40 × 60 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (3, 'Copper Seam', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://images.metmuseum.org/CRDImages/is/original/DP234125.jpg', 'Layla Nabulsi', '2022', 'Digital print', '120 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (3, 'Petra Blush', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://images.metmuseum.org/CRDImages/is/original/DP251139.jpg', 'Layla Nabulsi', '2024', 'Acrylic on wood', '90 × 90 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 4: The Weight of Jasmine (Omar)
  (4, 'Midnight Kufic', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://images.metmuseum.org/CRDImages/is/original/DP159194.jpg', 'Omar Khalil', '2020', 'Mixed media', '150 × 100 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (4, 'Urban Erosion', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://images.metmuseum.org/CRDImages/is/original/DP215472.jpg', 'Omar Khalil', '2023', 'Ink on paper', '60 × 80 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (4, 'The Pink House', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://images.metmuseum.org/CRDImages/is/original/DP215476.jpg', 'Omar Khalil', '2019', 'Photography', '180 × 120 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (4, 'Threshold Light', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://images.metmuseum.org/CRDImages/is/original/DP215480.jpg', 'Omar Khalil', '2021', 'Charcoal on linen', '50 × 70 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (4, 'Salt Flat', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://images.metmuseum.org/CRDImages/is/original/DP215484.jpg', 'Omar Khalil', '2024', 'Oil on canvas', '100 × 70 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 5: Geometric Meditations (Omar)
  (5, 'Rainbow Street Fragment', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://images.metmuseum.org/CRDImages/is/original/DP215488.jpg', 'Omar Khalil', '2022', 'Gouache on board', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (5, 'Arabesque No. 3', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1567.jpg', 'Omar Khalil', '2018', 'Watercolour on paper', '200 × 150 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (5, 'Black Iris', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1947.jpg', 'Omar Khalil', '2023', 'Digital print', '90 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (5, 'Wadi Mist', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://images.metmuseum.org/CRDImages/ep/original/DT46.jpg', 'Omar Khalil', '2021', 'Acrylic on wood', '60 × 80 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (5, 'The Old City Gate', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1502.jpg', 'Omar Khalil', '2024', 'Mixed media', '150 × 100 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 6: Wadi Rum Visions (Omar)
  (6, 'Burnt Umber Horizon', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://images.metmuseum.org/CRDImages/ep/original/DT375.jpg', 'Omar Khalil', '2019', 'Ink on paper', '40 × 60 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (6, 'Calligraphic Drift', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1976.jpg', 'Omar Khalil', '2022', 'Photography', '180 × 120 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (6, 'Stone Garden', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://images.metmuseum.org/CRDImages/ep/original/DT270.jpg', 'Omar Khalil', '2020', 'Charcoal on linen', '120 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (6, 'Olive Silence', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://www.artic.edu/iiif/2/25c31d8d-21a4-9ea1-1d73-6a2eca4dda7e/full/843,/0/default.jpg', 'Omar Khalil', '2023', 'Oil on canvas', '80 × 60 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (6, 'Muezzin Echo', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://www.artic.edu/iiif/2/1adf2696-8489-499b-cad2-821d7fde4b33/full/843,/0/default.jpg', 'Omar Khalil', '2024', 'Encaustic on panel', '100 × 70 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 7: Amman by Night (Sana)
  (7, 'The Balcony', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://www.artic.edu/iiif/2/831a05de-d3f6-f4fa-a460-23008dd58dda/full/843,/0/default.jpg', 'Sana al-Masri', '2021', 'Watercolour on paper', '60 × 80 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (7, 'Lapis Fragment', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://www.artic.edu/iiif/2/dec724f1-d5a1-e7ea-be48-aa2abbe8b304/full/843,/0/default.jpg', 'Sana al-Masri', '2018', 'Digital print', '200 × 150 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (7, 'Desert Mirror', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://www.artic.edu/iiif/2/9926d1ef-f5da-c4d7-8874-a3fa4427a006/full/843,/0/default.jpg', 'Sana al-Masri', '2023', 'Acrylic on wood', '90 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (7, 'Sunken Relief', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://www.artic.edu/iiif/2/a6b1cdb3-accf-e634-5179-2f2f4a8d6a74/full/843,/0/default.jpg', 'Sana al-Masri', '2022', 'Mixed media', '120 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (7, 'Lattice Study', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://www.artic.edu/iiif/2/e966799b-97ee-1cc6-bd2f-a94b4b8bb8f9/full/843,/0/default.jpg', 'Sana al-Masri', '2024', 'Gouache on board', '50 × 70 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 8: Calligraphy in Motion (Sana)
  (8, 'Bronze Age', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://www.artic.edu/iiif/2/73b2a70f-e83e-6a26-a0d5-5d3dac7d0e6f/full/843,/0/default.jpg', 'Sana al-Masri', '2020', 'Photography', '180 × 120 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (8, 'The Water Jug', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Hagia_Sofia_Iznik_tiles.JPG/800px-Hagia_Sofia_Iznik_tiles.JPG', 'Sana al-Masri', '2019', 'Charcoal on linen', '150 × 100 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (8, 'Pomegranate Season', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Arabesque_Topkapi_ms_H._2153_fol._29a.jpg/800px-Arabesque_Topkapi_ms_H._2153_fol._29a.jpg', 'Sana al-Masri', '2023', 'Oil on canvas', '60 × 80 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (8, 'Ash & Gold', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Alhambra_Patio_de_los_Arrayanes.jpg/800px-Alhambra_Patio_de_los_Arrayanes.jpg', 'Sana al-Masri', '2021', 'Watercolour on paper', '100 × 70 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (8, 'The Minaret', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Mamluk_Quran_BL_Add_MS_22406.jpg/800px-Mamluk_Quran_BL_Add_MS_22406.jpg', 'Sana al-Masri', '2024', 'Screen print', '40 × 60 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 9: The Roman Arch Revisited (Sana)
  (9, 'Night Geometry', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Mosque_lamp%2C_Egypt%2C_1350-60_AD%2C_gilded_and_enamelled_glass_-_Aga_Khan_Museum_-_Ontario%2C_Canada_-_DSC05049.jpg/800px-Mosque_lamp%2C_Egypt%2C_1350-60_AD%2C_gilded_and_enamelled_glass_-_Aga_Khan_Museum_-_Ontario%2C_Canada_-_DSC05049.jpg', 'Sana al-Masri', '2022', 'Digital print', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (9, 'Aqaba Spectrum', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Blackbird_on_Branch_by_Muhammad_Sadiq_Beg.jpg/800px-Blackbird_on_Branch_by_Muhammad_Sadiq_Beg.jpg', 'Sana al-Masri', '2018', 'Acrylic on wood', '200 × 150 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (9, 'Bedouin Embroidery', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Miraj_by_Sultan_Muhammad.jpg/800px-Miraj_by_Sultan_Muhammad.jpg', 'Sana al-Masri', '2023', 'Mixed media', '90 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (9, 'Terracotta Noon', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Leyla_and_Majnun_at_school.jpg/800px-Leyla_and_Majnun_at_school.jpg', 'Sana al-Masri', '2020', 'Ink on paper', '60 × 80 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (9, 'The Hammam', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Camille_Pissarro%2C_1897%2C_Boulevard_Montmartre%2C_Morning%2C_Grey_Weather%2C_oil_on_canvas%2C_73_x_92_cm%2C_National_Gallery_of_Victoria.jpg/1000px-thumbnail.jpg', 'Sana al-Masri', '2024', 'Photography', '150 × 100 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 10: Urban Palimpsest (Tariq)
  (10, 'Fig Season', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Claude_Monet%2C_Impression%2C_soleil_levant.jpg/1000px-Claude_Monet%2C_Impression%2C_soleil_levant.jpg', 'Tariq Hamdan', '2021', 'Charcoal on linen', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (10, 'Eastern Light Study', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://images.metmuseum.org/CRDImages/is/original/DP234125.jpg', 'Tariq Hamdan', '2019', 'Oil on canvas', '200 × 150 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (10, 'Weave & Thread', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://images.metmuseum.org/CRDImages/is/original/DP251139.jpg', 'Tariq Hamdan', '2023', 'Watercolour on paper', '50 × 70 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (10, 'Clay Memory', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://images.metmuseum.org/CRDImages/is/original/DP159194.jpg', 'Tariq Hamdan', '2022', 'Digital print', '100 × 70 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (10, 'Copper Twilight', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://images.metmuseum.org/CRDImages/is/original/DP215472.jpg', 'Tariq Hamdan', '2024', 'Acrylic on wood', '180 × 120 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 11: Shades of Umber (Tariq)
  (11, 'Amber at Dusk', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://images.metmuseum.org/CRDImages/is/original/DP215476.jpg', 'Tariq Hamdan', '2020', 'Mixed media', '60 × 80 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (11, 'The Limestone Veil', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://images.metmuseum.org/CRDImages/is/original/DP215480.jpg', 'Tariq Hamdan', '2018', 'Gouache on board', '120 × 90 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (11, 'Between Walls', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://images.metmuseum.org/CRDImages/is/original/DP215484.jpg', 'Tariq Hamdan', '2023', 'Ink on paper', '90 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (11, 'Jasmine Memory', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://images.metmuseum.org/CRDImages/is/original/DP215488.jpg', 'Tariq Hamdan', '2021', 'Photography', '200 × 150 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (11, 'Golden Hour Study', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1567.jpg', 'Tariq Hamdan', '2024', 'Charcoal on linen', '40 × 60 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 12: Beyond the Old City (Tariq)
  (12, 'Citadel Fragment', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1947.jpg', 'Tariq Hamdan', '2022', 'Oil on canvas', '100 × 70 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (12, 'Wadi Floor', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://images.metmuseum.org/CRDImages/ep/original/DT46.jpg', 'Tariq Hamdan', '2020', 'Watercolour on paper', '150 × 100 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (12, 'Ink & Silence', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1502.jpg', 'Tariq Hamdan', '2023', 'Digital print', '60 × 80 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (12, 'Geometric Prayer', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://images.metmuseum.org/CRDImages/ep/original/DT375.jpg', 'Tariq Hamdan', '2019', 'Acrylic on wood', '120 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (12, 'Amman Rooftops', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1976.jpg', 'Tariq Hamdan', '2024', 'Mixed media', '80 × 60 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 13: Salt & Stone (Reem)
  (13, 'Desert Hymn', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://images.metmuseum.org/CRDImages/ep/original/DT270.jpg', 'Reem Aziz', '2021', 'Encaustic on panel', '200 × 150 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (13, 'The Fig Tree', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://www.artic.edu/iiif/2/25c31d8d-21a4-9ea1-1d73-6a2eca4dda7e/full/843,/0/default.jpg', 'Reem Aziz', '2018', 'Ink on paper', '50 × 70 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (13, 'Shadow Letter', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://www.artic.edu/iiif/2/1adf2696-8489-499b-cad2-821d7fde4b33/full/843,/0/default.jpg', 'Reem Aziz', '2023', 'Photography', '180 × 120 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (13, 'Copper Seam', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://www.artic.edu/iiif/2/831a05de-d3f6-f4fa-a460-23008dd58dda/full/843,/0/default.jpg', 'Reem Aziz', '2022', 'Oil on canvas', '120 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (13, 'Petra Blush', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://www.artic.edu/iiif/2/dec724f1-d5a1-e7ea-be48-aa2abbe8b304/full/843,/0/default.jpg', 'Reem Aziz', '2024', 'Watercolour on paper', '90 × 90 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 14: Fragments of Memory (Reem)
  (14, 'Midnight Kufic', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://www.artic.edu/iiif/2/9926d1ef-f5da-c4d7-8874-a3fa4427a006/full/843,/0/default.jpg', 'Reem Aziz', '2020', 'Digital print', '60 × 80 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (14, 'Urban Erosion', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://www.artic.edu/iiif/2/a6b1cdb3-accf-e634-5179-2f2f4a8d6a74/full/843,/0/default.jpg', 'Reem Aziz', '2019', 'Acrylic on wood', '200 × 150 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (14, 'The Pink House', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://www.artic.edu/iiif/2/e966799b-97ee-1cc6-bd2f-a94b4b8bb8f9/full/843,/0/default.jpg', 'Reem Aziz', '2023', 'Mixed media', '100 × 70 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (14, 'Threshold Light', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://www.artic.edu/iiif/2/73b2a70f-e83e-6a26-a0d5-5d3dac7d0e6f/full/843,/0/default.jpg', 'Reem Aziz', '2021', 'Charcoal on linen', '150 × 100 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (14, 'Salt Flat', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1000px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg', 'Reem Aziz', '2024', 'Gouache on board', '40 × 60 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 15: Kufic Variations (Reem)
  (15, 'Rainbow Street Fragment', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/1000px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg', 'Reem Aziz', '2022', 'Screen print', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (15, 'Arabesque No. 3', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/800px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg', 'Reem Aziz', '2018', 'Oil on canvas', '80 × 60 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (15, 'Black Iris', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_Scream.jpg/800px-The_Scream.jpg', 'Reem Aziz', '2023', 'Watercolour on paper', '200 × 150 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (15, 'Wadi Mist', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg', 'Reem Aziz', '2020', 'Photography', '60 × 80 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (15, 'The Old City Gate', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg', 'Reem Aziz', '2024', 'Digital print', '90 × 90 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 16: Shadows on White (Khalid)
  (16, 'Burnt Umber Horizon', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/The_Lady_of_Shalott%2C_by_John_William_Waterhouse.jpg/800px-The_Lady_of_Shalott%2C_by_John_William_Waterhouse.jpg', 'Khalid Barakat', '2021', 'Acrylic on wood', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (16, 'Calligraphic Drift', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Klimt_The_Kiss.jpg/800px-Klimt_The_Kiss.jpg', 'Khalid Barakat', '2019', 'Mixed media', '180 × 120 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (16, 'Stone Garden', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg/800px-Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg', 'Khalid Barakat', '2023', 'Ink on paper', '50 × 70 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (16, 'Olive Silence', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Vassily_Kandinsky%2C_1913_-_Composition_7.jpg/1000px-Vassily_Kandinsky%2C_1913_-_Composition_7.jpg', 'Khalid Barakat', '2022', 'Photography', '100 × 70 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (16, 'Muezzin Echo', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Wassily_Kandinsky%2C_1926_-_Several_Circles%2C_Gugg_0910_25.jpg/800px-Wassily_Kandinsky%2C_1926_-_Several_Circles%2C_Gugg_0910_25.jpg', 'Khalid Barakat', '2024', 'Charcoal on linen', '150 × 100 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 17: The Olive Grove (Khalid)
  (17, 'The Balcony', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg/1000px-Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg', 'Khalid Barakat', '2020', 'Oil on canvas', '60 × 80 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (17, 'Lapis Fragment', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/800px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg', 'Khalid Barakat', '2018', 'Watercolour on paper', '200 × 150 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (17, 'Desert Mirror', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://images.metmuseum.org/CRDImages/is/original/DP234125.jpg', 'Khalid Barakat', '2023', 'Digital print', '90 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (17, 'Sunken Relief', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://images.metmuseum.org/CRDImages/is/original/DP251139.jpg', 'Khalid Barakat', '2021', 'Acrylic on wood', '120 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (17, 'Lattice Study', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://images.metmuseum.org/CRDImages/is/original/DP159194.jpg', 'Khalid Barakat', '2024', 'Mixed media', '40 × 60 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 18: Desert Chromatics (Khalid)
  (18, 'Bronze Age', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://images.metmuseum.org/CRDImages/is/original/DP215472.jpg', 'Khalid Barakat', '2022', 'Gouache on board', '80 × 60 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (18, 'The Water Jug', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://images.metmuseum.org/CRDImages/is/original/DP215476.jpg', 'Khalid Barakat', '2020', 'Ink on paper', '150 × 100 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (18, 'Pomegranate Season', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://images.metmuseum.org/CRDImages/is/original/DP215480.jpg', 'Khalid Barakat', '2023', 'Photography', '180 × 120 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (18, 'Ash & Gold', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://images.metmuseum.org/CRDImages/is/original/DP215484.jpg', 'Khalid Barakat', '2019', 'Oil on canvas', '100 × 70 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (18, 'The Minaret', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://images.metmuseum.org/CRDImages/is/original/DP215488.jpg', 'Khalid Barakat', '2024', 'Watercolour on paper', '60 × 80 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 19: Modern Arabesque (Dina)
  (19, 'Night Geometry', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1567.jpg', 'Dina Sabbagh', '2021', 'Digital print', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (19, 'Aqaba Spectrum', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1947.jpg', 'Dina Sabbagh', '2018', 'Acrylic on wood', '200 × 150 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (19, 'Bedouin Embroidery', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://images.metmuseum.org/CRDImages/ep/original/DT46.jpg', 'Dina Sabbagh', '2023', 'Mixed media', '50 × 70 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (19, 'Terracotta Noon', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1502.jpg', 'Dina Sabbagh', '2022', 'Charcoal on linen', '90 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (19, 'The Hammam', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://images.metmuseum.org/CRDImages/ep/original/DT375.jpg', 'Dina Sabbagh', '2024', 'Ink on paper', '150 × 100 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 20: Threshold (Dina)
  (20, 'Fig Season', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1976.jpg', 'Dina Sabbagh', '2020', 'Oil on canvas', '180 × 120 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (20, 'Eastern Light Study', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://images.metmuseum.org/CRDImages/ep/original/DT270.jpg', 'Dina Sabbagh', '2019', 'Watercolour on paper', '100 × 70 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (20, 'Weave & Thread', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://www.artic.edu/iiif/2/25c31d8d-21a4-9ea1-1d73-6a2eca4dda7e/full/843,/0/default.jpg', 'Dina Sabbagh', '2023', 'Digital print', '60 × 80 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (20, 'Clay Memory', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://www.artic.edu/iiif/2/1adf2696-8489-499b-cad2-821d7fde4b33/full/843,/0/default.jpg', 'Dina Sabbagh', '2021', 'Acrylic on wood', '120 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (20, 'Copper Twilight', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://www.artic.edu/iiif/2/831a05de-d3f6-f4fa-a460-23008dd58dda/full/843,/0/default.jpg', 'Dina Sabbagh', '2024', 'Photography', '200 × 150 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 21: Dead Sea Reflections (Dina)
  (21, 'Amber at Dusk', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://www.artic.edu/iiif/2/dec724f1-d5a1-e7ea-be48-aa2abbe8b304/full/843,/0/default.jpg', 'Dina Sabbagh', '2022', 'Encaustic on panel', '40 × 60 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (21, 'The Limestone Veil', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://www.artic.edu/iiif/2/9926d1ef-f5da-c4d7-8874-a3fa4427a006/full/843,/0/default.jpg', 'Dina Sabbagh', '2018', 'Mixed media', '80 × 60 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (21, 'Between Walls', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://www.artic.edu/iiif/2/a6b1cdb3-accf-e634-5179-2f2f4a8d6a74/full/843,/0/default.jpg', 'Dina Sabbagh', '2023', 'Gouache on board', '150 × 100 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (21, 'Jasmine Memory', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://www.artic.edu/iiif/2/e966799b-97ee-1cc6-bd2f-a94b4b8bb8f9/full/843,/0/default.jpg', 'Dina Sabbagh', '2020', 'Oil on canvas', '60 × 80 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (21, 'Golden Hour Study', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://www.artic.edu/iiif/2/73b2a70f-e83e-6a26-a0d5-5d3dac7d0e6f/full/843,/0/default.jpg', 'Dina Sabbagh', '2024', 'Watercolour on paper', '100 × 70 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 22: The Copper Hills (Yusuf)
  (22, 'Citadel Fragment', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1000px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg', 'Yusuf Nassar', '2021', 'Digital print', '180 × 120 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (22, 'Wadi Floor', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/1000px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg', 'Yusuf Nassar', '2019', 'Acrylic on wood', '50 × 70 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (22, 'Ink & Silence', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/800px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg', 'Yusuf Nassar', '2023', 'Mixed media', '200 × 150 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (22, 'Geometric Prayer', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_Scream.jpg/800px-The_Scream.jpg', 'Yusuf Nassar', '2022', 'Ink on paper', '90 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (22, 'Amman Rooftops', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg', 'Yusuf Nassar', '2024', 'Photography', '120 × 90 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 23: Petra at Dawn (Yusuf)
  (23, 'Desert Hymn', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg', 'Yusuf Nassar', '2020', 'Charcoal on linen', '60 × 80 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (23, 'The Fig Tree', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/The_Lady_of_Shalott%2C_by_John_William_Waterhouse.jpg/800px-The_Lady_of_Shalott%2C_by_John_William_Waterhouse.jpg', 'Yusuf Nassar', '2018', 'Oil on canvas', '150 × 100 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (23, 'Shadow Letter', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Klimt_The_Kiss.jpg/800px-Klimt_The_Kiss.jpg', 'Yusuf Nassar', '2023', 'Watercolour on paper', '200 × 150 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (23, 'Copper Seam', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg/800px-Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg', 'Yusuf Nassar', '2021', 'Digital print', '40 × 60 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (23, 'Petra Blush', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Vassily_Kandinsky%2C_1913_-_Composition_7.jpg/1000px-Vassily_Kandinsky%2C_1913_-_Composition_7.jpg', 'Yusuf Nassar', '2024', 'Acrylic on wood', '100 × 70 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 24: Jabal Qal'a (Yusuf)
  (24, 'Burnt Umber Horizon', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Wassily_Kandinsky%2C_1926_-_Several_Circles%2C_Gugg_0910_25.jpg/800px-Wassily_Kandinsky%2C_1926_-_Several_Circles%2C_Gugg_0910_25.jpg', 'Yusuf Nassar', '2022', 'Mixed media', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (24, 'Calligraphic Drift', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg/1000px-Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg', 'Yusuf Nassar', '2020', 'Ink on paper', '180 × 120 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (24, 'Stone Garden', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/800px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg', 'Yusuf Nassar', '2023', 'Photography', '60 × 80 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (24, 'Olive Silence', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://images.metmuseum.org/CRDImages/is/original/DP234125.jpg', 'Yusuf Nassar', '2019', 'Oil on canvas', '150 × 100 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (24, 'Muezzin Echo', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://images.metmuseum.org/CRDImages/is/original/DP251139.jpg', 'Yusuf Nassar', '2024', 'Watercolour on paper', '80 × 60 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 25: Aqaba Blue (Nour)
  (25, 'The Balcony', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://images.metmuseum.org/CRDImages/is/original/DP159194.jpg', 'Nour Jamal', '2021', 'Digital print', '200 × 150 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (25, 'Lapis Fragment', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://images.metmuseum.org/CRDImages/is/original/DP215472.jpg', 'Nour Jamal', '2018', 'Acrylic on wood', '50 × 70 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (25, 'Desert Mirror', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://images.metmuseum.org/CRDImages/is/original/DP215476.jpg', 'Nour Jamal', '2023', 'Mixed media', '100 × 70 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (25, 'Sunken Relief', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://images.metmuseum.org/CRDImages/is/original/DP215480.jpg', 'Nour Jamal', '2022', 'Charcoal on linen', '120 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (25, 'Lattice Study', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://images.metmuseum.org/CRDImages/is/original/DP215484.jpg', 'Nour Jamal', '2024', 'Ink on paper', '90 × 90 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 26: The Black Iris Garden (Nour)
  (26, 'Bronze Age', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://images.metmuseum.org/CRDImages/is/original/DP215488.jpg', 'Nour Jamal', '2020', 'Oil on canvas', '180 × 120 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (26, 'The Water Jug', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1567.jpg', 'Nour Jamal', '2019', 'Watercolour on paper', '60 × 80 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (26, 'Pomegranate Season', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1947.jpg', 'Nour Jamal', '2023', 'Digital print', '200 × 150 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (26, 'Ash & Gold', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://images.metmuseum.org/CRDImages/ep/original/DT46.jpg', 'Nour Jamal', '2022', 'Acrylic on wood', '40 × 60 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (26, 'The Minaret', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1502.jpg', 'Nour Jamal', '2024', 'Photography', '100 × 70 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 27: Jerash in Ruins (Nour)
  (27, 'Night Geometry', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://images.metmuseum.org/CRDImages/ep/original/DT375.jpg', 'Nour Jamal', '2021', 'Encaustic on panel', '120 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (27, 'Aqaba Spectrum', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://images.metmuseum.org/CRDImages/ep/original/DT1976.jpg', 'Nour Jamal', '2018', 'Mixed media', '150 × 100 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (27, 'Bedouin Embroidery', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://images.metmuseum.org/CRDImages/ep/original/DT270.jpg', 'Nour Jamal', '2023', 'Gouache on board', '80 × 60 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (27, 'Terracotta Noon', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://www.artic.edu/iiif/2/25c31d8d-21a4-9ea1-1d73-6a2eca4dda7e/full/843,/0/default.jpg', 'Nour Jamal', '2020', 'Oil on canvas', '200 × 150 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (27, 'The Hammam', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://www.artic.edu/iiif/2/1adf2696-8489-499b-cad2-821d7fde4b33/full/843,/0/default.jpg', 'Nour Jamal', '2024', 'Watercolour on paper', '60 × 80 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 28: Wadi Faynan Gold (Ibrahim)
  (28, 'Fig Season', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://www.artic.edu/iiif/2/831a05de-d3f6-f4fa-a460-23008dd58dda/full/843,/0/default.jpg', 'Ibrahim Qasim', '2022', 'Digital print', '90 × 90 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (28, 'Eastern Light Study', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://www.artic.edu/iiif/2/dec724f1-d5a1-e7ea-be48-aa2abbe8b304/full/843,/0/default.jpg', 'Ibrahim Qasim', '2020', 'Ink on paper', '120 × 90 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (28, 'Weave & Thread', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://www.artic.edu/iiif/2/9926d1ef-f5da-c4d7-8874-a3fa4427a006/full/843,/0/default.jpg', 'Ibrahim Qasim', '2023', 'Photography', '180 × 120 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (28, 'Clay Memory', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://www.artic.edu/iiif/2/a6b1cdb3-accf-e634-5179-2f2f4a8d6a74/full/843,/0/default.jpg', 'Ibrahim Qasim', '2021', 'Acrylic on wood', '100 × 70 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (28, 'Copper Twilight', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://www.artic.edu/iiif/2/e966799b-97ee-1cc6-bd2f-a94b4b8bb8f9/full/843,/0/default.jpg', 'Ibrahim Qasim', '2024', 'Charcoal on linen', '50 × 70 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 29: Bougainvillea Fall (Ibrahim)
  (29, 'Amber at Dusk', 'A meditative exploration of negative space and the light that pools in the crevices of old stone.', 'https://www.artic.edu/iiif/2/73b2a70f-e83e-6a26-a0d5-5d3dac7d0e6f/full/843,/0/default.jpg', 'Ibrahim Qasim', '2019', 'Oil on canvas', '200 × 150 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (29, 'The Limestone Veil', 'Drawn from field studies made at dawn, this work captures the transient chromatics of the Jordanian plateau.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Hagia_Sofia_Iznik_tiles.JPG/800px-Hagia_Sofia_Iznik_tiles.JPG', 'Ibrahim Qasim', '2023', 'Watercolour on paper', '60 × 80 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (29, 'Between Walls', 'A visual record of absence — the marks, scratches, and layered histories found on a single wall in Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Arabesque_Topkapi_ms_H._2153_fol._29a.jpg/800px-Arabesque_Topkapi_ms_H._2153_fol._29a.jpg', 'Ibrahim Qasim', '2021', 'Digital print', '120 × 90 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (29, 'Jasmine Memory', 'The artist spent three months developing this palette from natural pigments sourced in Wadi Rum.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Alhambra_Patio_de_los_Arrayanes.jpg/800px-Alhambra_Patio_de_los_Arrayanes.jpg', 'Ibrahim Qasim', '2024', 'Mixed media', '90 × 90 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (29, 'Golden Hour Study', 'Calligraphic strokes dissolve into pure abstraction, retaining only the muscle memory of the letter.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Mamluk_Quran_BL_Add_MS_22406.jpg/800px-Mamluk_Quran_BL_Add_MS_22406.jpg', 'Ibrahim Qasim', '2022', 'Encaustic on panel', '150 × 100 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false),

  -- Gallery 30: Letters to the Levant (Ibrahim)
  (30, 'Citadel Fragment', 'An intimate portrait of urban life caught between tradition and accelerating change in downtown Amman.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Mosque_lamp%2C_Egypt%2C_1350-60_AD%2C_gilded_and_enamelled_glass_-_Aga_Khan_Museum_-_Ontario%2C_Canada_-_DSC05049.jpg/800px-Mosque_lamp%2C_Egypt%2C_1350-60_AD%2C_gilded_and_enamelled_glass_-_Aga_Khan_Museum_-_Ontario%2C_Canada_-_DSC05049.jpg', 'Ibrahim Qasim', '2020', 'Photography', '180 × 120 cm', -1.8, 1.5, -4.4, 0, 1.0, false),
  (30, 'Wadi Floor', 'Geometric order meets organic fracture, echoing the tension in Levantine architecture across centuries.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Blackbird_on_Branch_by_Muhammad_Sadiq_Beg.jpg/800px-Blackbird_on_Branch_by_Muhammad_Sadiq_Beg.jpg', 'Ibrahim Qasim', '2018', 'Oil on canvas', '100 × 70 cm', 0.0, 1.5, -4.4, 0, 1.0, false),
  (30, 'Ink & Silence', 'The composition emerged from improvised mark-making during a residency in the salt flats of the Dead Sea.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Miraj_by_Sultan_Muhammad.jpg/800px-Miraj_by_Sultan_Muhammad.jpg', 'Ibrahim Qasim', '2023', 'Watercolour on paper', '200 × 150 cm', 1.8, 1.5, -4.4, 0, 1.0, false),
  (30, 'Geometric Prayer', 'Layers of translucent glaze build a chromatic depth reminiscent of ancient Mamluk illuminated manuscripts.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Leyla_and_Majnun_at_school.jpg/800px-Leyla_and_Majnun_at_school.jpg', 'Ibrahim Qasim', '2021', 'Digital print', '60 × 80 cm', -4.4, 1.5, -1.5, 1.5708, 1.0, false),
  (30, 'Amman Rooftops', 'A tribute to the artisans whose craft — invisible in the finished building — underpins an entire visual culture.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Camille_Pissarro%2C_1897%2C_Boulevard_Montmartre%2C_Morning%2C_Grey_Weather%2C_oil_on_canvas%2C_73_x_92_cm%2C_National_Gallery_of_Victoria.jpg/1000px-thumbnail.jpg', 'Ibrahim Qasim', '2024', 'Acrylic on wood', '120 × 90 cm', 4.4, 1.5, -1.5, -1.5708, 1.0, false);

COMMIT;
